import {
  matAddRound, matArrowRightAltRound, matBoltRound, matChatRound,
  matCheckCircleRound, matContentCutRound, matDeleteRound, matEditRound,
  matHelpRound, matHomeRound, matImportContactsRound, matLightModeRound,
  matMenuRound, matRocketLaunchRound, matSendRound, matSentimentNeutralRound,
  matSubjectRound, matTipsAndUpdatesRound, matTranslateRound, matArrowDownwardRound,
  matWarningRound, matCheckRound, matCloseRound, matFaceRound, matLogoutRound,
  matExpandMoreRound, matFolderRound, matChevronRightRound, matCreateNewFolderRound,
  matFolderDeleteRound, matTopicRound, matNoteAddRound, matDescriptionRound, matFileCopyRound,
  matSaveRound, matThumbUpRound, matRefreshRound, matAutoAwesomeRound, matSearchRound,
  matForumRound, matAutoStoriesRound
} from "@ng-icons/material-icons/round";

export const MAT_ICON_LIST: Record<string, string> = {
  matHomeRound,
  matMenuRound,
  matRocketLaunchRound,
  matSubjectRound,
  matContentCutRound,
  matTranslateRound,
  matImportContactsRound,
  matSendRound,
  matWarningRound,
  matHelpRound,
  matTipsAndUpdatesRound,
  matCheckCircleRound,
  matAddRound,
  matChatRound,
  matDeleteRound,
  matEditRound,
  matLightModeRound,
  matBoltRound,
  matSentimentNeutralRound,
  matArrowRightAltRound,
  matArrowDownwardRound,
  matCheckRound,
  matCloseRound,
  matFaceRound,
  matLogoutRound,
  matExpandMoreRound,
  matFolderRound,
  matChevronRightRound,
  matCreateNewFolderRound,
  matFolderDeleteRound,
  matTopicRound,
  matNoteAddRound,
  matDescriptionRound,
  matFileCopyRound,
  matSaveRound,
  matThumbUpRound,
  matRefreshRound,
  matAutoAwesomeRound,
  matSearchRound,
  matForumRound,
  matAutoStoriesRound,
}
